Feat/update v0.4.1
ofek/coincurve pull request #132
Opened 2023-12-26 18:22 UTC by MementoRC

Mainly add support for the new features of SECP256K1.

   - Replaced deprecated functions.
   - Moved project description to TOML (is that ok?)
   - Added tox test for python 3.12
   - 
The .h are created automatically from the sec256pk1 with gcc -E (and a few tricks) so it formats a little oddly, creating lots of changes (like int* a -> int *a) which may make the review tedious
In the conda recipe (and the github repo for libsecp256k1-py-bindings), the build.py was modified to make it more automated and able to add either dynamic or static Clib. The compilation also uses an ABI version of CFFI lib

2023-12-26 18:43 UTC, ofek commented
Let's update:

- https://github.com/ofek/coincurve/blob/2dfea673835e524ffaeb11dc1c2aecaf23188195/.github/workflows/build.yml#L41 to `3.12`
- Every `pypa/cibuildwheel@v2.11.2` to `pypa/cibuildwheel@v2.16.2`

2023-12-26 20:41 UTC, MementoRC commented
@ofek, Oh, we were on the same wavelength. I broke the conda-forge recipe though, I am trying to fix it

2023-12-31 18:33 UTC, ofek commented
Is this ready for review/merge?

2023-12-31 19:40 UTC, MementoRC commented
@ofek, yes, it passes the conda recipe checks as well

2024-01-09 15:24 UTC, MementoRC commented
@ofek Are there channges needed?

2024-01-11 03:13 UTC, ofek requested changes

2024-01-11 03:13 UTC, ofek commented on pyproject.toml
> +requires = ["setuptools>=61", "cffi>=1.3.0", "urllib3>2"]
```suggestion
requires = ["setuptools>=61", "cffi>=1.3.0"]
```

2024-01-11 03:38 UTC, ofek requested changes

2024-01-11 03:38 UTC, ofek commented on setup.py
> +        subprocess.run([python_exe, build_script, c_file, '0'], shell=False, check=True)  # noqa S603
```suggestion
        subprocess.run([sys.executable, build_script, c_file, '0'], shell=False, check=True)  # noqa S603
```

2024-01-11 04:04 UTC, ofek approved these changes
Thank you very much!

2024-01-11 04:04 UTC, merged

2024-01-11 14:56 UTC, ofek commented
https://github.com/ofek/coincurve/releases/tag/v19.0.0