(feat) refactor tests with fixture
ofek/coincurve pull request #146
Opened 2024-02-25 22:39 UTC by MementoRC

The purpose is to be able to run pytest with the `cibuildwheel` feature. cibuildwheel install the tests in a manner that prevent `tests` to be recognized as a package and thus there is pretty much no way to `import samples` (at least none within the 50 commits I made on my branch to test it out!)

2024-02-26 15:44 UTC, ofek requested changes

2024-02-26 15:44 UTC, ofek commented on tests/test_bench.py
> +    signature = samples.get('SIGNATURE')
Please change everything to use direct lookup `samples['SIGNATURE']`

2024-03-04 17:37 UTC, MementoRC commented
This should help enable the full pytest test-suite for the built the wheels with cibuildwheel

2024-03-04 17:38 UTC, ofek approved these changes

2024-03-04 17:38 UTC, merged