FEAT: from setup to pyproject
ofek/coincurve pull request #161
Opened 2024-03-19 22:09 UTC by MementoRC

Let's try to transition more metadate from setup to pyproject, this way when we hatch, it'll be simpler and both setuptools and hatchling may be tested in quasi-parallel

2024-03-19 22:12 UTC, MementoRC commented
Oh ... that will fail with the windows build (remembering why I didn't PR earlier ...) - Oh, well we'll see the low-commit PR is an elusive mistress

2024-03-20 00:25 UTC, ofek requested changes

2024-03-20 00:25 UTC, ofek commented on .github/scripts/build-windows-wheels.sh
> +python -m build --wheel -C="--build-option=bdist_wheel" -C="--build-option=--plat-name" -C="--build-option=win_amd64"
![image](https://github.com/ofek/coincurve/assets/9677399/68b8f1d6-54f3-4af6-afd9-c99416416e93)

2024-03-20 15:52 UTC, ofek approved these changes

2024-03-20 15:53 UTC, MementoRC commented
@ofek I stumbled upon a lot of discussions about build systems, maybe at some point we should use `scikit-build`?

2024-03-20 15:58 UTC, merged